"""initial schema

Revision ID: f6023f36d0ea
Revises: 
Create Date: 2026-07-16 11:02:50.413613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6023f36d0ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_question_index', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('interview_model', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interviews_candidate_id'), 'ai_interviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_ai_interviews_job_id'), 'ai_interviews', ['job_id'], unique=False)
    op.create_table('parsed_resumes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('full_name_confidence', sa.Float(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_confidence', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('phone_confidence', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('location_confidence', sa.Float(), nullable=True),
    sa.Column('total_experience_years', sa.Float(), nullable=True),
    sa.Column('total_experience_confidence', sa.Float(), nullable=True),
    sa.Column('work_history', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('skills_confidence', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsing_model', sa.String(), nullable=True),
    sa.Column('parsing_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('parsing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('needs_human_review', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_resumes_candidate_id'), 'parsed_resumes', ['candidate_id'], unique=False)
    op.create_table('skill_extractions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('extraction_model', sa.String(), nullable=True),
    sa.Column('extraction_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('extraction_duration_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_extractions_source_id'), 'skill_extractions', ['source_id'], unique=False)
    op.create_table('answer_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interview_id', sa.String(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('follow_up_suggestions', sa.JSON(), nullable=True),
    sa.Column('evaluation_model', sa.String(), nullable=True),
    sa.Column('evaluation_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('evaluation_duration_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['ai_interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fitment_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('resume_id', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('overall_reasoning', sa.Text(), nullable=False),
    sa.Column('skills_score', sa.Float(), nullable=True),
    sa.Column('skills_reasoning', sa.Text(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('experience_reasoning', sa.Text(), nullable=True),
    sa.Column('education_score', sa.Float(), nullable=True),
    sa.Column('education_reasoning', sa.Text(), nullable=True),
    sa.Column('culture_fit_score', sa.Float(), nullable=True),
    sa.Column('culture_fit_reasoning', sa.Text(), nullable=True),
    sa.Column('scoring_model', sa.String(), nullable=True),
    sa.Column('scoring_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('scoring_duration_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['parsed_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitment_scores_candidate_id'), 'fitment_scores', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_fitment_scores_job_id'), 'fitment_scores', ['job_id'], unique=False)
    op.create_table('screened_resumes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resume_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('meets_requirements', sa.Integer(), nullable=True),
    sa.Column('screening_reasoning', sa.Text(), nullable=True),
    sa.Column('screening_score', sa.Float(), nullable=True),
    sa.Column('criteria_match', sa.JSON(), nullable=True),
    sa.Column('screening_model', sa.String(), nullable=True),
    sa.Column('screening_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('screening_duration_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['parsed_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screened_resumes_job_id'), 'screened_resumes', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screened_resumes_job_id'), table_name='screened_resumes')
    op.drop_table('screened_resumes')
    op.drop_index(op.f('ix_fitment_scores_job_id'), table_name='fitment_scores')
    op.drop_index(op.f('ix_fitment_scores_candidate_id'), table_name='fitment_scores')
    op.drop_table('fitment_scores')
    op.drop_table('answer_evaluations')
    op.drop_index(op.f('ix_skill_extractions_source_id'), table_name='skill_extractions')
    op.drop_table('skill_extractions')
    op.drop_index(op.f('ix_parsed_resumes_candidate_id'), table_name='parsed_resumes')
    op.drop_table('parsed_resumes')
    op.drop_index(op.f('ix_ai_interviews_job_id'), table_name='ai_interviews')
    op.drop_index(op.f('ix_ai_interviews_candidate_id'), table_name='ai_interviews')
    op.drop_table('ai_interviews')
    # ### end Alembic commands ###
