"""add fitment summary fields

Revision ID: a1b2c3d4e5f6
Revises: f6023f36d0ea
Create Date: 2026-07-22 23:23:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'f6023f36d0ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitment_scores', sa.Column('strengths', sa.JSON(), nullable=True))
    op.add_column('fitment_scores', sa.Column('weaknesses', sa.JSON(), nullable=True))
    op.add_column('fitment_scores', sa.Column('recommendations', sa.Text(), nullable=True))
    op.add_column('fitment_scores', sa.Column('fit_verdict', sa.String(), nullable=True))
    op.add_column('fitment_scores', sa.Column('consider_because', sa.JSON(), nullable=True))
    op.add_column('fitment_scores', sa.Column('not_consider_because', sa.JSON(), nullable=True))
    op.add_column('fitment_scores', sa.Column('suitable_roles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fitment_scores', 'suitable_roles')
    op.drop_column('fitment_scores', 'not_consider_because')
    op.drop_column('fitment_scores', 'consider_because')
    op.drop_column('fitment_scores', 'fit_verdict')
    op.drop_column('fitment_scores', 'recommendations')
    op.drop_column('fitment_scores', 'weaknesses')
    op.drop_column('fitment_scores', 'strengths')
    # ### end Alembic commands ###
